baseURL = "/"
languageCode = "en-us"
title = "Phil in the Blank"
theme = "hugo-theme-notrack"
newContentEditor = "nvim"
mainSections = ["blog"]
# disqusShortname = "example"
paginate = 25
summaryLength = 10

[params]
  author = "Phil"
  siteHeading = "Phil in the Blank" # defaults to author
  showBlogLatest = true
  mainSections = ["blog"]
  showTaxonomyLinks = false
  nBlogLatest = 7 # number of blog post on the home page
  blogLatestHeading = "Recent Posts"
  poemLatestHeading = "Recent Poems"
  nPoemLatest = 7
  showPoemLatest = true
  
  [params.social]
    github = "example"
    linkedin = "example"
    email = "example@example.com"
    mastodon = "example"
    medium = "example"
    keybase = "example"

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"
